'''
Parsing utility for Tango .xmi files.

'''

from lxml import etree

import models

class TangoXmiParser:
    '''
    Parses .xmi files generated by Pogo
    '''

    def __init__(self, file_name):
        self.file_name = file_name
        self.tree = etree.parse(file_name)

    def get_device_server(self):
        '''
        Return a device server model from the parsed file
        :return: device server object created from the file
        '''

        # TODO: Implement
        return None
    def get_device_classes(self):
        '''
        Parse the .xmi file for classes definitions
        :return:
        '''
        # TODO: Implement
        return None

    def get_device_class_info(self, cl):
        '''
        Return info realated to class
        :param cl: name or DeviceClass object for which the info has to be retrived
        :return: DevicClassInfo objec
        '''
        # TODO: Implement
        return None

    def get_device_attributes(self, cl):
        '''
        Retrun list of attributes for class cl
        :param cl: name or DeviceClass obejct
        :return: list of DeviceAttribute obejcts
        '''
        # TODO: Implement
        return None

    def get_device_commands(self, cl):
        '''
        Retrun list of attributes for class cl
        :param cl: name or DeviceClass obejct
        :return: list of DeviceAttribute obejcts
        '''
        # TODO: Implement
        return None