'''
Parsing utility for Tango .xmi files.

'''

from lxml import etree

import models

class TangoXmiParser:
    '''
    Parses .xmi files generated by Pogo
    '''

    def __init__(self, file_name):
        self.file_name = file_name
        self.tree = etree.parse(file_name)

    def get_device_server(self):
        '''
        Return a device server model from the parsed file
        :return: device server object created from the file
        '''

        # TODO: Implement
        return None